repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]
  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: local
    hooks:
    - id: pyright
      name: pyright
      stages: [commit]
      types: [python]
      entry: pyright
      language: system
      pass_filenames: false
      always_run: true
    - id: pytest
      name: pytest
      stages: [commit]
      types: [python]
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      verbose: true  # Show pytest output
      args: [ -s ]  # Make pytest output stdout
exclude: ^(poetry\.lock)